In [1]:
import numpy as np
import pandas as pd

##DF인덱스조작

In [3]:
np.random.seed(2022)
data=np.vstack([list('ABCDE'),np.random.rand(3,5).round(2)])
data

array([['A', 'B', 'C', 'D', 'E'],
       ['0.01', '0.5', '0.11', '0.05', '0.69'],
       ['0.49', '0.9', '0.65', '0.9', '0.72'],
       ['0.83', '0.83', '0.83', '0.96', '0.37']], dtype='<U32')

In [4]:
data.T

array([['A', '0.01', '0.49', '0.83'],
       ['B', '0.5', '0.9', '0.83'],
       ['C', '0.11', '0.65', '0.83'],
       ['D', '0.05', '0.9', '0.96'],
       ['E', '0.69', '0.72', '0.37']], dtype='<U32')

In [5]:
df=pd.DataFrame(data.T,columns='C1 C2 C3 C4'.split())
df

  C1    C2    C3    C4
0  A  0.01  0.49  0.83
1  B   0.5   0.9  0.83
2  C  0.11  0.65  0.83
3  D  0.05   0.9  0.96
4  E  0.69  0.72  0.37

In [6]:
df.set_index('C1',inplace=True)
df

      C2    C3    C4
C1
A   0.01  0.49  0.83
B    0.5   0.9  0.83
C   0.11  0.65  0.83
D   0.05   0.9  0.96
E   0.69  0.72  0.37

In [8]:
df.index.name='index'
df

         C2    C3    C4
index
A      0.01  0.49  0.83
B       0.5   0.9  0.83
C      0.11  0.65  0.83
D      0.05   0.9  0.96
E      0.69  0.72  0.37

In [9]:
df.reset_index(inplace=True)
df

  index    C2    C3    C4
0     A  0.01  0.49  0.83
1     B   0.5   0.9  0.83
2     C  0.11  0.65  0.83
3     D  0.05   0.9  0.96
4     E  0.69  0.72  0.37

In [10]:
filename='서울시CCTV설치운영현황(자치구)_년도별_211231기준.csv'
cctv=pd.read_csv(filename,skiprows=1,encoding='EUC-KR')

In [11]:
cctv.head(2)

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,계,"83,557","4,812","1,851","3,434","4,295","6,840","8,708","11,572","10,627","12,267","11,247","7,904"
1,종로구,"1,715",815,NaN,NaN,195,150,0,261,85,9,200,0

In [12]:
#계 행을 삭제
cctv.drop([0],inplace=True)
cctv.head(2)

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
1,종로구,"1,715",815,NaN,NaN,195,150,0,261,85,9,200,0
2,중 구,"2,447",16,114,87,77,236,240,372,386,155,361,403

In [13]:
cctv.set_index('구분',inplace=True)
cctv.head(2)

,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
구분,,,,,,,,,,,,
종로구,"1,715",815,NaN,NaN,195,150,0,261,85,9,200,0
중 구,"2,447",16,114,87,77,236,240,372,386,155,361,403

In [14]:
cctv.index.name='자치구'
cctv.head(2)

,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
자치구,,,,,,,,,,,,
종로구,"1,715",815,NaN,NaN,195,150,0,261,85,9,200,0
중 구,"2,447",16,114,87,77,236,240,372,386,155,361,403

In [23]:
#'중 구'를 '중구'로 바꾸기
cctv.index=cctv.index.str.replace(' ','')
cctv.index[1]

'중구'

In [24]:
cctv.head()

,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
자치구,,,,,,,,,,,,
종로구,"1,715",815,NaN,NaN,195,150,0,261,85,9,200,0
중구,"2,447",16,114,87,77,236,240,372,386,155,361,403
용산구,"2,611",34,71,234,125,221,298,351,125,307,617,228
성동구,"3,829",163,144,208,107,325,255,967,415,490,472,283
광진구,"3,211",35,57,100,187,98,52,675,465,712,175,655