#pandas DataFrame

In [1]:
import numpy as np
import pandas as pd

##데이터프레임

In [2]:
data={
    '국어':[80,90,70,30],
    '영어':[90,70,60,40],
    '수학':[90,60,80,70]
}

In [3]:
pd.Series(data)

국어    [80, 90, 70, 30]
영어    [90, 70, 60, 40]
수학    [90, 60, 80, 70]
dtype: object

In [4]:
df=pd.DataFrame(data)
df

   국어  영어  수학
0  80  90  90
1  90  70  60
2  70  60  80
3  30  40  70

In [5]:
df.index=['춘향','몽룡','향단','방자']
df

    국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [10]:
np.random.seed(2022)
df2=pd.DataFrame(np.random.randint(40,101,12).reshape(4,3),columns=['국어','영어','수학'],index=['춘향','몽룡','향단','방자'])
df2

    국어  영어  수학
춘향  68  85  88
몽룡  89  89  88
향단  95  64  58
방자  64  56  93

*반복문을 써서 만드는 경우

In [13]:
kor=[]
eng=[]
mat=[]
#kor,eng,mat=[],[],[]
for i in range(4):
  kor.append(np.random.randint(40,101))
  eng.append(np.random.randint(40,101))
  mat.append(np.random.randint(40,101))
kor

[56, 63, 63, 92]

In [14]:
pd.DataFrame({'국어':kor,'영어':eng,'수학':mat})

   국어  영어  수학
0  56  93  55
1  63  77  57
2  63  61  77
3  92  96  90

##데이터프레임 인덱싱

In [15]:
df

    국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [16]:
df['국어']  #시리즈

춘향    80
몽룡    90
향단    70
방자    30
Name: 국어, dtype: int64

In [17]:
df.국어

춘향    80
몽룡    90
향단    70
방자    30
Name: 국어, dtype: int64

In [18]:
df.국어.향단

70

In [19]:
df['국어']['방자']

30

In [20]:
df['국어'][3]  #방자

30

#슬라이스

In [23]:
df

    국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [22]:
df['국어'][:2]

춘향    80
몽룡    90
Name: 국어, dtype: int64

In [24]:
df[['국어','영어']]

    국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [27]:
df[['국어']][:2]

    국어
춘향  80
몽룡  90

* loc, iloc 인덱서  : [행인덱스,열인덱스]

In [32]:
#loc 사용법
#df.loc['몽룡','영어']
#df.loc['몽룡']['영어']
#df.loc['몽룡'][1]
df.loc['몽룡'].영어   # 모두 70이 나옴

70

* iloc 인덱서 : [행숫자 인덱스, 열숫자 인덱스]

In [35]:
df.iloc[1,1], df.iloc[1][1]

(70, 70)

In [37]:
df.iloc[1]['영어'], df.iloc[1].영어

(70, 70)

In [38]:
df.iloc[:2,1:]

    영어  수학
춘향  90  90
몽룡  70  60

In [49]:
#방자의 수학점수 인덱싱
print(df['수학']['방자'],df['수학'].방자,df.수학.방자,df.수학[3])
print(df.loc['방자']['수학'],df.loc['방자'].수학,df.loc['방자'][2])
print(df.iloc[3,2],df.iloc[3].수학,df.iloc[3][2],df.iloc[3]['수학'])
print(df.loc['방자'][-1],df.iloc[-1][-1])

70 70 70 70
70 70 70
70 70 70 70
70 70

값 변경

In [50]:
df

    국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [51]:
df['국어']['방자']=80
df

    국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  80  40  70

In [52]:
df.영어.방자=85
df

    국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  80  85  70

* 열 추가

In [53]:
df['과학']=[40.3,80.4,75.3,68.5]
df

    국어  영어  수학    과학
춘향  80  90  90  40.3
몽룡  90  70  60  80.4
향단  70  60  80  75.3
방자  80  85  70  68.5

In [58]:
#df.평균=[10,20,30,40]  에러발생함
df['평균']=df.mean(axis=1)
df

    국어  영어  수학    과학      평균
춘향  80  90  90  40.3  75.075
몽룡  90  70  60  80.4  75.100
향단  70  60  80  75.3  71.325
방자  80  85  70  68.5  75.875

In [59]:
del df['평균']
df

    국어  영어  수학    과학
춘향  80  90  90  40.3
몽룡  90  70  60  80.4
향단  70  60  80  75.3
방자  80  85  70  68.5

In [62]:
df.drop(columns=['수학','과학'])

    국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  80  85

In [68]:
#실제 df에 적용하기 위해서
df.drop(columns=['수학'],inplace=True)
df

    국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  80  85

* 행삭제

In [69]:
df.drop(['방자'])

    국어  영어
춘향  80  90
몽룡  90  70
향단  70  60

In [70]:
df.drop(['향단'],inplace=True)

In [71]:
df

    국어  영어
춘향  80  90
몽룡  90  70
방자  80  85

In [72]:
import seaborn as sns 
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
def hide_numbers(s):
    if(len(s) < 5):
        return s
    else:
        return '*' + hide_numbers(s[1:])
    #함수를 완성해 별이를 도와주세요

# 아래는 테스트로 출력해 보기 위한 코드입니다.
print("결과 : " + hide_numbers('01033334444'));

결과 : *******4444

In [ ]:
def solution(x):
    A=list(x).sum
    if(x%A==0):
        return True
    else:
        False

In [24]:
x=123

x_s=str(123)
x_s
s=0
for i in range(len(x_s)):
  s+=int(x_s[i])
s

6